############################################################
########### Workflow: Document Build and Release ###########
############################################################

########## AUTHOR: Jan Rother
########## DATE:   2025-07

name: Build and Release PDF Document from LaTeX

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Date and Time
        id: datetime
        run: echo "DATETIME=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Compile LaTeX Document
        id: compile_document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: assignment.tex
          docker_image: janrother/latex-environment:latest
          pre_compile: "tlmgr update --self || true && tlmgr update --all || true && git lfs fetch --all && git lfs pull"

      - name: Upload PDF Document
        id: upload_document
        uses: actions/upload-artifact@v4
        with:
          name: assignment
          path: out/assignment.pdf
          overwrite: 'true'

      - name: Release PDF Document
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TAG_NAME: 'thesis_${{ steps.datetime.outputs.DATETIME }}'
          RELEASE_NAME: 'Thesis (${{ steps.datetime.outputs.DATETIME }})'
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false

      - name: Upload PDF Document to Release
        id: upload_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out/assignment.pdf
          asset_name: assignment.pdf
          asset_content_type: application/pdf